### ISSUE TITLE
possessive names

### ISSUE THREAD

**Issue by christopherpickering** [trollepierre/names-extractor#1]
Hey @trollepierre this is cool, thank you!

I found a small issue -

for the text "this is Joe Smith's car", the name comes out as "Joe Smith's", but should be "Joe Smith".

for text "the company is Cars and Trucks", gives "Cars" and "Trucks", but should be "Cars and Trucks".

for text "the company has a Very Long Name", gives "Very Long" and "Long Name", but should give "Very Long Name".

Thanks!

**Comment by christopherpickering** [comment]
On the possessive.. if it is possessive on any word except the last, maybe it should be kept? "Joe's Auto Works"

**Comment by trollepierre** [comment]
Hello @christopherpickering ,
Thank you for opening issues in this repository.
I am not maintaining the repository, but if you want to PR the bugs you found, I can quick merge if needed.

**Comment by christopherpickering** [comment]
thanks @trollepierre! I will send a pr pretty soon.
